### ISSUE TITLE
Crash randomly after rendering TexView

### ISSUE THREAD

**Issue by willemstuijt** [shah-xad/flutter_tex#110]
More or less 1 out of the 8 times I render LaTeX with TeXView my app crashes when running on a Moto One (Android). It is very random.

E/AndroidRuntime(13787): FATAL EXCEPTION: main
E/AndroidRuntime(13787): Process: com.app.my_app, PID: 13787
E/AndroidRuntime(13787): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
E/AndroidRuntime(13787): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1625)
E/AndroidRuntime(13787): 	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1864)
E/AndroidRuntime(13787): 	at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1183)
E/AndroidRuntime(13787): 	at io.flutter.plugins.d.l2$a.run(Unknown Source:42)
E/AndroidRuntime(13787): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(13787): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(13787): 	at android.os.Looper.loop(Looper.java:241)
E/AndroidRuntime(13787): 	at android.app.ActivityThread.main(ActivityThread.java:7617)
E/AndroidRuntime(13787): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13787): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(13787): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

flutter doctor -v:
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.4.0-91-generic, locale en_US.UTF-8)
    • Flutter version 2.5.3 at /home/willem/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/willem/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • motorola one action (mobile) • ZY326HZHGM • android-arm64  • Android 10 (API 29)
    • Linux (desktop)              • linux      • linux-x64      • Ubuntu 20.04.3 LTS 5.4.0-91-generic
    • Chrome (web)                 • chrome     • web-javascript • Google Chrome 96.0.4664.45

• No issues found!

**Comment by gaurav822** [comment]
I'm also getting the same issue.
