### ISSUE TITLE
Mathjax syntax with link cannot be displayed

### ISSUE THREAD

**Issue by IhwanID** [shah-xad/flutter_tex#53]
Hey @shah-xad , i don't know why my syntax mathjax can be loaded again in this new package version (^3.6.1+2). 

i guess this because my syntax contains a link, for example:

```
"""<p>Hvilke af følgende hører til de naturlige tal (betegnet&nbsp;<math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi mathvariant="normal">ℕ</mi><annotation encoding="application/vnd.wiris.mtweb-params+json">{"autoformat":true}</annotation></semantics></math>)?</p>"""
```

but my other syntax that does not contain link is working fine.

and all my syntax in version ^3.6.1+3 is not working anymore. this is I get in the console:
```
path: satisfied (Path is satisfied), interface: en0
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(loadUrl_failed, Failed parsing the URL, Request was: '{
    headers = "<null>";
    url = "http://localhost:5353/packages/flutter_tex/src/flutter_tex_libs/katex/index.html?teXViewServerPort=5353&viewInstanceCount=6&configurations=\"{}\"&urlRawTeXHTML=%7B%22children%22%3A%5B%7B%22id%22%3Anull%2C%22children%22%3A%5B%7B%22id%22%3Anull%2C%22data%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cp%3EHvilke%20af%20f%C3%B8lgende%20h%C3%B8rer%20til%20de%20naturlige%20tal%20(betegnet%26nbsp%3B%3Cmath%20xmlns%3D%5C%22http%3A%2F%2Fwww.w3.org%2F1998%2FMath%2FMathML%5C%22%3E%3Csemantics%3E%3Cmi%20mathvariant%3D%5C%22normal%5C%22%3E%E2%84%95%3C%2Fmi%3E%3Cannotation%20encoding%3D%5C%22application%2Fvnd.wiris.mtweb-params%2Bjson%5C%22%3E%7B%5C%22autoformat%5C%22%3Atrue%7D%3C%2Fannotation%3E%3C%2Fsemantics%3E%3C%2Fmath%3E)%3F%3C%2Fp%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%2C%22style%22%3A%22font-size%3A%202<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(loadUrl_failed, Failed parsing the URL, Request was: '{
    headers = "<null>";
    url = "http://localhost:5354/packages/flutter_tex/src/flutter_tex_libs/katex/index.html?teXViewServerPort=5354&viewInstanceCount=6&configurations=\"{}\"&urlRawTeXHTML=%7B%22children%22%3A%5B%7B%22id%22%3A%22container_0%22%2C%22children%22%3A%5B%7B%22id%22%3Anull%2C%22data%22%3A%22%3Cp%3E%3Cmath%3E%3Cmrow%3E%3Cmo%3E-%3C%2Fmo%3E%3Cmn%3E692%3C%2Fmn%3E%3C%2Fmrow%3E%3C%2Fmath%3E%3C%2Fp%3E%22%2C%22style%22%3A%22color%3A%20rgba(0%2C%200%2C%200%2C%20255)%3Bbackground-color%3A%20rgba(255%2C%20255%2C%20255%2C%20255)%3Btext-align%3A%20center%3B%22%7D%5D%2C%22style%22%3Anull%7D%5D%2C%22style%22%3A%22padding%3A%2010px%3Bheight%3A%20100px%3Bbox-shadow%3A%200%2010px%2010px%200%20rgba(0%2C0%2C0%2C0.2)%3Bbackground-color%3A%20rgba(255%2C%20255%2C%20255%2C%20255)%3B%22%7D";
}')
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(loadUrl_failed, Failed parsing the URL, Request was: '{
    headers = "<null>";
    url = "http://localhost:5355/packages/flutter_tex/src/flutter_tex_libs/katex/index.html?teXViewServerPort=5355&viewInstanceCount=6&configurations=\"{}\"&urlRawTeXHTML=%7B%22children%22%3A%5B%7B%22id%22%3A%22container_0%22%2C%22children%22%3A%5B%7B%22id%22%3Anull%2C%22data%22%3A%22%3Cp%3E%3Cmath%3E%3Cmrow%3E%3Cmfrac%3E%3Cmn%3E135%3C%2Fmn%3E%3Cmn%3E88%3C%2Fmn%3E%3C%2Fmfrac%3E%3C%2Fmrow%3E%3C%2Fmath%3E%3C%2Fp%3E%22%2C%22style%22%3A%22color%3A%20rgba(0%2C%200%2C%200%2C%20255)%3Bbackground-color%3A%20rgba(255%2C%20255%2C%20255%2C%20255)%3Btext-align%3A%20center%3B%22%7D%5D%2C%22style%22%3Anull%7D%5D%2C%22style%22%3A%22padding%3A%2010px%3Bheight%3A%20100px%3Bbox-shadow%3A%200%2010px%2010px%200%20rgba(0%2C0%2C0%2C0.2)%3Bbackground-color%3A%20rgba(255%2C%20255%2C%20255%2C%20255)%3B%22%7D";
}')
#0      StandardMethodCodec.decodeEnvelope (package:flutter/s<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(loadUrl_failed, Failed parsing the URL, Request was: '{
    headers = "<null>";
    url = "http://localhost:5356/packages/flutter_tex/src/flutter_tex_libs/katex/index.html?teXViewServerPort=5356&viewInstanceCount=6&configurations=\"{}\"&urlRawTeXHTML=%7B%22children%22%3A%5B%7B%22id%22%3A%22container_0%22%2C%22children%22%3A%5B%7B%22id%22%3Anull%2C%22data%22%3A%22%3Cp%3E%3Cmath%3E%3Cmrow%3E%3Cmn%3E263%3C%2Fmn%3E%3C%2Fmrow%3E%3C%2Fmath%3E%3C%2Fp%3E%22%2C%22style%22%3A%22color%3A%20rgba(0%2C%200%2C%200%2C%20255)%3Bbackground-color%3A%20rgba(255%2C%20255%2C%20255%2C%20255)%3Btext-align%3A%20center%3B%22%7D%5D%2C%22style%22%3Anull%7D%5D%2C%22style%22%3A%22padding%3A%2010px%3Bheight%3A%20100px%3Bbox-shadow%3A%200%2010px%2010px%200%20rgba(0%2C0%2C0%2C0.2)%3Bbackground-color%3A%20rgba(255%2C%20255%2C%20255%2C%20255)%3B%22%7D";
}')
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1     <…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(loadUrl_failed, Failed parsing the URL, Request was: '{
    headers = "<null>";
    url = "http://localhost:5357/packages/flutter_tex/src/flutter_tex_libs/katex/index.html?teXViewServerPort=5357&viewInstanceCount=6&configurations=\"{}\"&urlRawTeXHTML=%7B%22children%22%3A%5B%7B%22id%22%3A%22container_0%22%2C%22children%22%3A%5B%7B%22id%22%3Anull%2C%22data%22%3A%22%3Cp%3EIngen%3C%2Fp%3E%22%2C%22style%22%3A%22color%3A%20rgba(0%2C%200%2C%200%2C%20255)%3Bbackground-color%3A%20rgba(255%2C%20255%2C%20255%2C%20255)%3Btext-align%3A%20center%3B%22%7D%5D%2C%22style%22%3Anull%7D%5D%2C%22style%22%3A%22padding%3A%2010px%3Bheight%3A%20100px%3Bbox-shadow%3A%200%2010px%2010px%200%20rgba(0%2C0%2C0%2C0.2)%3Bbackground-color%3A%20rgba(255%2C%20255%2C%20255%2C%20255)%3B%22%7D";
}')
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platf<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(loadUrl_failed, Failed parsing the URL, Request was: '{
    headers = "<null>";
    url = "http://localhost:5358/packages/flutter_tex/src/flutter_tex_libs/katex/index.html?teXViewServerPort=5358&viewInstanceCount=6&configurations=\"{}\"&urlRawTeXHTML=%7B%22children%22%3A%5B%7B%22id%22%3A%22container_0%22%2C%22children%22%3A%5B%7B%22id%22%3Anull%2C%22data%22%3A%22%3Cp%3E%3Cmath%3E%3Cmrow%3E%3Cmi%20mathvariant%3D%5C%22normal%5C%22%3E%26%23960%3B%3C%2Fmi%3E%3C%2Fmrow%3E%3C%2Fmath%3E%3C%2Fp%3E%22%2C%22style%22%3A%22color%3A%20rgba(0%2C%200%2C%200%2C%20255)%3Bbackground-color%3A%20rgba(255%2C%20255%2C%20255%2C%20255)%3Btext-align%3A%20center%3B%22%7D%5D%2C%22style%22%3Anull%7D%5D%2C%22style%22%3A%22padding%3A%2010px%3Bheight%3A%20100px%3Bbox-shadow%3A%200%2010px%2010px%200%20rgba(0%2C0%2C0%2C0.2)%3Bbackground-color%3A%20rgba(255%2C%20255%2C%20255%2C%20255)%3B%22%7D";
}')
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src<…>
```

**Comment by shah-xad** [comment]
I am sorry currently, there's an issue of support of `MathML` format, Flutter TeX is using MathJax2.7 minified library because actual MathJax is very huge. So it's lacking some features. Mathjax3.0 is fine in size but that's not properly ready to put here. You can follow #25 .

**Comment by IhwanID** [comment]
nice @shah-xad , i really depend on this package. is there anything that i can help / contribute to make this feature happened. i see in this old version package i can load my syntax well but i don't know why right now there's no something appear when i load the sample code in README.md. 

my flutter version is 1.17.1

**Comment by shah-xad** [comment]
Can you point me to that particular version where it was working fine? Because It's an old issue that MathML syntax doesn't work, and I didn't make any change in MathJax library it's still same from the initial release.
