### ISSUE TITLE
 I use a lot of TeXView, crash by DeadSystemException. device restart 

### ISSUE THREAD

**Issue by liujiakuoyx** [shah-xad/flutter_tex#75]
2020-08-13 15:25:25.350 733-851/? E/SurfaceFlinger: AddClientLayer failed, mNumLayers (4096) >= MAX_LAYERS (4096)
2020-08-13 15:25:25.350 1408-2677/? E/SurfaceComposerClient: SurfaceComposerClient::createSurface error Out of memory
2020-08-13 15:25:25.351 1408-2677/? E/WindowManager: Window Session Crash
    android.view.Surface$OutOfResourcesException
        at android.view.SurfaceControl.nativeCreate(libmapleframework.so:3461732)
        at android.view.SurfaceControl.<init>(libmapleframework.so:3462576)
        at android.view.SurfaceControl.<init>(libmapleframework.so:3463024)
        at android.view.SurfaceControl$Builder.build(libmapleframework.so:3463664)
        at com.android.server.wm.WindowContainer.onParentChanged(libmapleservices.so:4632240)
        at com.android.server.wm.DisplayContent$TaskStackContainers.onParentChanged(libmapleservices.so:1261504)
        at com.android.server.wm.WindowContainer.setParent(libmapleservices.so:4641904)
        at com.android.server.wm.WindowContainer.addChild(libmapleservices.so:4575144)
        at com.android.server.wm.DisplayContent.<init>(libmapleservices.so:1268540)
        at com.android.server.HwServiceFactoryImpl.createDisplayContent(libmaplehwServices.so:1561892)
        at com.android.server.HwServiceFactory.createDisplayContent(libmapleservices.so:1129476)
        at com.android.server.wm.RootWindowContainer.createDisplayContent(libmapleservices.so:1272180)
        at com.android.server.wm.WindowManagerService.getDisplayContentOrCreate(libmapleservices.so:4237044)
        at com.android.server.wm.WindowManagerService.addWindow(libmapleservices.so:4189564)
        at com.android.server.wm.HwWindowManagerService.addWindow(libmaplehwServices.so:2264852)
        at com.android.server.wm.Session.addToDisplay(libmapleservices.so:4183168)
        at android.view.IWindowSession$Stub.onTransact(libmapleframework.so:3561856)
        at com.android.server.wm.Session.onTransact(libmapleservices.so:4758392)
        at android.os.Binder.execTransactInternal(libmapleframework.so:5520784)
        at android.os.Binder.execTransact(libmapleframework.so:5519996)
2020-08-13 15:25:25.351 1408-2677/? E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    android.view.Surface$OutOfResourcesException
        at android.view.SurfaceControl.nativeCreate(libmapleframework.so:3461732)
        at android.view.SurfaceControl.<init>(libmapleframework.so:3462576)
        at android.view.SurfaceControl.<init>(libmapleframework.so:3463024)
        at android.view.SurfaceControl$Builder.build(libmapleframework.so:3463664)
        at com.android.server.wm.WindowContainer.onParentChanged(libmapleservices.so:4632240)
        at com.android.server.wm.DisplayContent$TaskStackContainers.onParentChanged(libmapleservices.so:1261504)
        at com.android.server.wm.WindowContainer.setParent(libmapleservices.so:4641904)
        at com.android.server.wm.WindowContainer.addChild(libmapleservices.so:4575144)
        at com.android.server.wm.DisplayContent.<init>(libmapleservices.so:1268540)
        at com.android.server.HwServiceFactoryImpl.createDisplayContent(libmaplehwServices.so:1561892)
        at com.android.server.HwServiceFactory.createDisplayContent(libmapleservices.so:1129476)
        at com.android.server.wm.RootWindowContainer.createDisplayContent(libmapleservices.so:1272180)
        at com.android.server.wm.WindowManagerService.getDisplayContentOrCreate(libmapleservices.so:4237044)
        at com.android.server.wm.WindowManagerService.addWindow(libmapleservices.so:4189564)
        at com.android.server.wm.HwWindowManagerService.addWindow(libmaplehwServices.so:2264852)
        at com.android.server.wm.Session.addToDisplay(libmapleservices.so:4183168)
        at android.view.IWindowSession$Stub.onTransact(libmapleframework.so:3561856)
        at com.android.server.wm.Session.onTransact(libmapleservices.so:4758392)
        at android.os.Binder.execTransactInternal(libmapleframework.so:5520784)
        at android.os.Binder.execTransact(libmapleframework.so:5519996)
2020-08-13 15:25:25.352 10226-10226/com.youdao.u_course E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.RuntimeException: InputChannel is not initialized.
        at android.view.InputEventReceiver.nativeInit(Native Method)
        at android.view.InputEventReceiver.<init>(InputEventReceiver.java:89)
        at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:8190)
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1065)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:447)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
        at android.app.Dialog.show(Dialog.java:475)
        at android.app.Presentation.show(Presentation.java:250)
        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
        at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:170)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:363)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
2020-08-13 15:25:25.353 10226-10463/com.youdao.u_course E/flutter: [ERROR:flutter/shell/common/shell.cc(209)] Dart Error: Unhandled exception:
    PlatformException(error, InputChannel is not initialized., null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
    #3      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039:54)
    #4      AndroidViewController.create (package:flutter/src/services/platform_views.dart:746:11)
    #5      TextureAndroidViewController.create (package:flutter/src/services/platform_views.dart:1017:34)
    #6      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1001:14)
    #7      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:176:29)
    #8      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:157:5)
    #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1748:9)
    #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #14     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:270:13)
    #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
    #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #20     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:827:17)
    #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #26     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #32     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:765:15)
    #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #34     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:765:15)
    #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #36     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
    #37     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
    #38     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
    #39     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
    #40     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
    #41     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
    #42     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
    #43     SchedulerBinding.handleDrawFrame (packa
2020-08-13 15:25:25.373 1408-1434/? E/AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.ui
    java.lang.IllegalArgumentException: Can't map token=WindowToken{48b4a8d android.os.BinderProxy@48b8f21} to display=Display 459 name="flutter-vd" already mapped to display=Display 459 info=DisplayInfo{"flutter-vd, displayId 459", uniqueId "virtual:com.youdao.u_course,10231,flutter-vd,2", app 535 x 3, real 535 x 3, largest app 535 x 535, smallest app 3 x 3, mode 460, defaultMode 460, modes [{id=460, width=535, height=3, fps=60.0}], colorMode 0, supportedColorModes [0], hdrCapabilities null, rotation 0, density 480 (480.0 x 480.0) dpi, layerStack 459, appVsyncOff 0, presDeadline 16666666, type VIRTUAL, state ON, owner com.youdao.u_course (uid 10231), FLAG_PRIVATE, removeMode 1} stacks=[com.android.server.wm.DisplayContent$NonAppWindowContainers@48d30e5, com.android.server.wm.DisplayContent$TaskStackContainers@48d6e81, com.android.server.wm.DisplayContent$AboveAppWindowContainers@46ebdbe, com.android.server.wm.DisplayContent$NonAppWindowContainers@48d30fb] tokens={android.os.BinderProxy@48b8f21=WindowToken{48b4a8d android.os.BinderProxy@48b8f21}}
        at com.android.server.wm.DisplayContent.addWindowToken(DisplayContent.java:1160)
        at com.android.server.wm.DisplayContent.reParentWindowToken(DisplayContent.java:1218)
        at com.android.server.wm.WindowToken.onDisplayChanged(WindowToken.java:283)
        at com.android.server.wm.WindowContainer.onDisplayChanged(WindowContainer.java:559)
        at com.android.server.wm.WindowContainer.onDisplayChanged(WindowContainer.java:559)
        at com.android.server.wm.DisplayContent.onDisplayChanged(DisplayContent.java:2495)
        at com.android.server.wm.DisplayContent.updateDisplayInfo(DisplayContent.java:2490)
        at com.android.server.wm.ActivityDisplay.onDisplayChanged(ActivityDisplay.java:225)
        at com.android.server.wm.RootActivityContainer.onDisplayChanged(RootActivityContainer.java:1511)
        at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:720)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:66)
        at com.android.server.ServiceThread.run(ServiceThread.java:40)
        at com.android.server.UiThread.run(UiThread.java:42)
2020-08-13 15:25:25.377 733-851/? E/SurfaceFlinger: AddClientLayer failed, mNumLayers (4096) >= MAX_LAYERS (4096)
2020-08-13 15:25:25.378 1408-9781/? E/SurfaceComposerClient: SurfaceComposerClient::createSurface error Out of memory
2020-08-13 15:25:25.378 1408-9781/? E/WindowManager: Window Session Crash
    android.view.Surface$OutOfResourcesException
        at android.view.SurfaceControl.nativeCreate(libmapleframework.so:3461732)
        at android.view.SurfaceControl.<init>(libmapleframework.so:3462576)
        at android.view.SurfaceControl.<init>(libmapleframework.so:3463024)
        at android.view.SurfaceControl$Builder.build(libmapleframework.so:3463664)
        at com.android.server.wm.DisplayContent.<init>(libmapleservices.so:1267940)
        at com.android.server.HwServiceFactoryImpl.createDisplayContent(libmaplehwServices.so:1561892)
        at com.android.server.HwServiceFactory.createDisplayContent(libmapleservices.so:1129476)
        at com.android.server.wm.RootWindowContainer.createDisplayContent(libmapleservices.so:1272180)
        at com.android.server.wm.WindowManagerService.getDisplayContentOrCreate(libmapleservices.so:4237044)
        at com.android.server.wm.WindowManagerService.addWindow(libmapleservices.so:4189564)
        at com.android.server.wm.HwWindowManagerService.addWindow(libmaplehwServices.so:2264852)
        at com.android.server.wm.Session.addToDisplay(libmapleservices.so:4183168)
        at android.view.IWindowSession$Stub.onTransact(libmapleframework.so:3561856)
        at com.android.server.wm.Session.onTransact(libmapleservices.so:4758392)
        at android.os.Binder.execTransactInternal(libmapleframework.so:5520784)
        at android.os.Binder.execTransact(libmapleframework.so:5519996)
2020-08-13 15:25:25.378 1408-9781/? E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    android.view.Surface$OutOfResourcesException
        at android.view.SurfaceControl.nativeCreate(libmapleframework.so:3461732)
        at android.view.SurfaceControl.<init>(libmapleframework.so:3462576)
        at android.view.SurfaceControl.<init>(libmapleframework.so:3463024)
        at android.view.SurfaceControl$Builder.build(libmapleframework.so:3463664)
        at com.android.server.wm.DisplayContent.<init>(libmapleservices.so:1267940)
        at com.android.server.HwServiceFactoryImpl.createDisplayContent(libmaplehwServices.so:1561892)
        at com.android.server.HwServiceFactory.createDisplayContent(libmapleservices.so:1129476)
        at com.android.server.wm.RootWindowContainer.createDisplayContent(libmapleservices.so:1272180)
        at com.android.server.wm.WindowManagerService.getDisplayContentOrCreate(libmapleservices.so:4237044)
        at com.android.server.wm.WindowManagerService.addWindow(libmapleservices.so:4189564)
        at com.android.server.wm.HwWindowManagerService.addWindow(libmaplehwServices.so:2264852)
        at com.android.server.wm.Session.addToDisplay(libmapleservices.so:4183168)
        at android.view.IWindowSession$Stub.onTransact(libmapleframework.so:3561856)
        at com.android.server.wm.Session.onTransact(libmapleservices.so:4758392)
        at android.os.Binder.execTransactInternal(libmapleframework.so:5520784)
        at android.os.Binder.execTransact(libmapleframework.so:5519996)
2020-08-13 15:25:25.379 10226-10226/com.youdao.u_course E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.RuntimeException: InputChannel is not initialized.
        at android.view.InputEventReceiver.nativeInit(Native Method)
        at android.view.InputEventReceiver.<init>(InputEventReceiver.java:89)
        at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:8190)
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1065)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:447)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
        at android.app.Dialog.show(Dialog.java:475)
        at android.app.Presentation.show(Presentation.java:250)
        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
        at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:170)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:363)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
2020-08-13 15:25:25.382 10226-10463/com.youdao.u_course E/flutter: [ERROR:flutter/shell/common/shell.cc(209)] Dart Error: Unhandled exception:
    PlatformException(error, InputChannel is not initialized., null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
    #3      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039:54)
    #4      AndroidViewController.create (package:flutter/src/services/platform_views.dart:746:11)
    #5      TextureAndroidViewController.create (package:flutter/src/services/platform_views.dart:1017:34)
    #6      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1001:14)
    #7      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:176:29)
    #8      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:157:5)
    #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1748:9)
    #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #14     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:270:13)
    #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
    #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #20     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:827:17)
    #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #26     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #32     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:765:15)
    #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #34     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:765:15)
    #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #36     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
    #37     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
    #38     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
    #39     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
    #40     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
    #41     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
    #42     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
    #43     SchedulerBinding.handleDrawFrame (packa
2020-08-13 15:25:25.387 964-4956/? E/libc: Access denied finding property "persist.mygote.disable"
2020-08-13 15:25:25.513 2208-2593/? E/AndroidRuntime: FATAL EXCEPTION: OllieServiceThread
    Process: com.huawei.systemserver, PID: 2208
    DeadSystemException: The system died; earlier logs will point to the root cause
2020-08-13 15:25:25.534 885-918/? E/emcomd: [EMCOMD_Socket] ProcessCommandsCallback# EOS.  Closing command socket.
2020-08-13 15:25:25.536 6889-8380/? E/HARDCODER: [localsocket.h,loop:198]"loop, recv error, fd:114, ret:0, errno:0"
2020-08-13 15:25:25.536 6889-8380/? E/HARDCODER: [client.h,recvEvent:161]"LocalsocketClient recvEvent EVENT_ERROR: uid:0, path:(null), fd:114. Reconnect now."
2020-08-13 15:25:25.598 6233-6508/? E/HARDCODER: [localsocket.h,loop:198]"loop, recv error, fd:126, ret:0, errno:0"
2020-08-13 15:25:25.598 6233-6508/? E/HARDCODER: [client.h,recvEvent:161]"LocalsocketClient recvEvent EVENT_ERROR: uid:0, path:(null), fd:126. Reconnect now."
2020-08-13 15:25:25.779 2287-4280/? E/UidNetStatBpfReader: get netstats from systemserver error
2020-08-13 15:25:25.779 2287-4280/? E/UidNetStatReader: updateNetStats and not find netInfo!
2020-08-13 15:25:25.860 970-29568/? E/FusionD: (OnGnssJniDied:56):on_gnss_jni_died
2020-08-13 15:25:25.861 708-708/? E/GnssHAL_AGpsSuplFqdnInterface: HWAGpsSuplFqdn was dead, start clear
2020-08-13 15:25:25.861 708-708/? E/HIGNSS_ADAPTER: Navigation start/stop count: -1, doesn't match!
2020-08-13 15:25:25.861 1303-1303/? E/Zygote: Exit zygote because system server (pid 1408) has terminated
2020-08-13 15:25:25.862 10226-10226/com.youdao.u_course E/MethodChannel#flutter/platform_views: Failed to handle method call

**Comment by sudeshkumara** [comment]
@liujiakuoyx  First of all, don't use more than one TexView on a single screen (you can, but this is my opinion). B'coz it initiates a web view each time and uses high processing power, then your app will slow, In my experience normally this DeadObjectException happens with AdMob ads (WebViews) when doing frequent orientation changes whilst the ad is loading. In the same way, in this case, you are trying to render a lot of content using TexViews. So change your code architecture. No suggestion can be made without seeing your code

**Comment by thanhkhanhcntt** [comment]
> @liujiakuoyx First of all, don't use more than one TexView on a single screen (you can, but this is my opinion). B'coz it initiates a web view each time and uses high processing power, then your app will slow, In my experience normally this DeadObjectException happens with AdMob ads (WebViews) when doing frequent orientation changes whilst the ad is loading. In the same way, in this case, you are trying to render a lot of content using TexViews. So change your code architecture. No suggestion can be made without seeing your code

I'm facing the same problem. My screen display about 40 math questions (include answers). If I use single TeXView and put all content into it (via TeXColumn and TeXDocument), the app will be crashed. But when I chunk about 5 questions in to a chunk, mean I use 8 TeXView, app run slow, but not crash, it must be better than using single TeXView.

**Comment by liujiakuoyx** [comment]
> > @liujiakuoyx First of all, don't use more than one TexView on a single screen (you can, but this is my opinion). B'coz it initiates a web view each time and uses high processing power, then your app will slow, In my experience normally this DeadObjectException happens with AdMob ads (WebViews) when doing frequent orientation changes whilst the ad is loading. In the same way, in this case, you are trying to render a lot of content using TexViews. So change your code architecture. No suggestion can be made without seeing your code
> 
> I'm facing the same problem. My screen display about 40 math questions (include answers). If I use single TeXView and put all content into it (via TeXColumn and TeXDocument), the app will be crashed. But when I chunk about 5 questions in to a chunk, mean I use 8 TeXView, app run slow, but not crash, it must be better than using single TeXView.

I finally chose H5 to achieve
