### ISSUE TITLE
Flutter Tex web support issue fixed + Android issue

### ISSUE THREAD

**Issue by ComputelessComputer** [shah-xad/flutter_tex#89]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:**
Yes, I am.

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
**Answer:**
Yes, I have.

======================================================================
### Basic Information about app
- I am working on an app that renders quizzes where I get the data in a json format.
- I use the json to render different parts of the quiz and puzzle them up in a list of TeXViewWidgets.
- I use only one TeXView to render the quiz.
- I have added all the needed parts for the manifest file.
- Works fine with iOS devices

### Issue
- When I run `flutter run --release` and deploy the app to my android device (Samsung Galaxy Note 10),  an error occurs and the quiz does **not** render at all.

### Question
1. Any proposition of what might have gone wrong?
2. Is there anyone else encountering this problem?

#### Results from `flutter doctor --verbose`
```
[✓] Flutter (Channel master, 1.25.0-9.0.pre.42, on macOS 11.1 20C69 darwin-x64, locale ko-KR)
    • Flutter version 1.25.0-9.0.pre.42 at /Users/jeongjiheon/development/flutter
    • Framework revision a76bb1a08e (5 weeks ago), 2020-12-12 00:17:51 -0700
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jeongjiheon/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Users/jeongjiheon/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 87.0.4280.141
```

#### Error message when texview renders
```
E/flutter (19479): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter (19479):      at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(Unknown Source:229)
E/flutter (19479):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(Unknown Source:152)
E/flutter (19479):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(Unknown Source:149)
E/flutter (19479):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/flutter (19479):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
E/flutter (19479):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (19479):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (19479):      at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (19479):      at android.os.Looper.loop(Looper.java:197)
E/flutter (19479):      at android.app.ActivityThread.main(ActivityThread.java:8167)
E/flutter (19479):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (19479):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/flutter (19479):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/flutter (19479): , null, null)
E/flutter (19479): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
E/flutter (19479): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:162)
E/flutter (19479): <asynchronous suspension>
E/flutter (19479): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1037)
E/flutter (19479): <asynchronous suspension>
E/flutter (19479): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:743)
E/flutter (19479): <asynchronous suspension>
E/flutter (19479): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:195)
E/flutter (19479): <asynchronous suspension>
E/flutter (19479): 
```

**Comment by ComputelessComputer** [comment]
I think I fixed the web support issue please check the [link](https://github.com/ComputelessComputer/flutter_tex)

**Comment by ComputelessComputer** [comment]
However there is still an unresolved issue with the android release mode. I have added the default options, but it just doesn't seem to render at all. Here is the debug log.

```
D/ConnectivityManager( 9578): requestNetwork; CallingUid : 10502, CallingPid : 9578
D/PhoneWindow( 9578): forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4274 com.android.internal.policy.DecorView.updateColorViews:1547 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3252 android.view.Window.setFlags:1153 com.android.internal.policy.PhoneWindow.generateLayout:2474
I/MultiWindowDecorSupport( 9578): [INFO] isPopOver = false
I/MultiWindowDecorSupport( 9578): updateCaptionType >> DecorView@f9bd828[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/MultiWindowDecorSupport( 9578): setCaptionType = 0, DecorView = DecorView@f9bd828[]
I/ViewRootImpl@189f372[MainActivity]( 9578): setView = com.android.internal.policy.DecorView@f9bd828 TM=true MM=false
V/InputMethodManager( 9578): Not IME target window, ignoring
I/ViewRootImpl@189f372[MainActivity]( 9578): Relayout returned: old=(0,0,975,3) new=(0,0,975,3) req=(975,3)0 dur=6 res=0x7 s={true 494659829760} ch=true
D/OpenGLRenderer( 9578): createReliableSurface : 0x734fef0e00(0x732c060000)
I/mali_winsys( 9578): new_window_surface() [975x3] return: 0x3000
D/OpenGLRenderer( 9578): eglCreateWindowSurface : 0x731074d080
E/DecorView( 9578): mWindow.mActivityCurrentConfig is null
D/OpenGLRenderer( 9578): makeCurrent EglSurface : 0x0 -> 0x731074d080
I/ViewRootImpl@189f372[MainActivity]( 9578): MSG_RESIZED: frame=(0,0,975,3) ci=(0,0,0,0) vi=(0,0,0,0) or=2
I/flutter ( 9578): Error: Unable to load asset: favicon.ico
```
